"""Importing this package registers every chunk type."""

from . import (  # noqa: F401
    flat,
    gap,
    spike_pit,
    patrol_platform,
    stairs,
    bump,
    falling_hazard,
    goal,
    ability_pickup,
    boost_pad,
    platform,
    ice_floor,
    vertical_column,
    one_way_platform,
    spring,
    checkpoint,
    crumbling_platform,
    moving_platform,
    pushable_box,
    key,
    door,
    swinging_hazard,
    charger_platform,
    spike_wall,
    cannon_lane,
    box_lava_gap,
    box_spring_trampoline,
    box_spring_relay,
)
